export { default as Home } from './Home/Home'
export { default as ContactBtn } from './ContactBtn/ContactBtn'
export { default as Navbar } from './Navbar/Navbar'
export { default as ContactModal } from './ContactModal/ContactModal'
export { default as AboutMe } from './AboutMe/AboutMe'
export { default as Footer } from './Footer/Footer'
export { default as SEO } from './SEO/SEO'